<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Terms &amp; Conditions | AgentHub</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@600;700&display=swap');
 :root{--bg:#0c0f17;--line:rgba(255,255,255,.1);--text:#f3f6ff;--muted:#a5adbd}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;color:var(--text);font-family:'DM Sans',sans-serif;background:var(--bg);overflow-x:hidden}a{color:inherit;text-decoration:none}
.legal-shell{position:relative;min-height:100vh}.legal-shell:before,.legal-shell:after{display:none}
.legal-nav{position:relative;z-index:2;width:min(1280px,calc(100% - 80px));margin:0 auto;height:78px;display:flex;align-items:center}.brand{display:flex;align-items:center;gap:11px;font-family:'Space Grotesk',sans-serif;font-size:20px;font-weight:700}.brand-mark{display:grid;place-items:center;width:40px;height:40px;border-radius:10px;background:#6658f5}.brand-mark svg{width:23px;height:23px}.brand-accent{color:#8b72ff}
.legal-page{position:relative;z-index:1;width:min(820px,calc(100% - 40px));margin:0 auto;padding:54px 0 70px}.intro-grid{display:block}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:7px 16px;border:1px solid #394154;border-radius:20px;color:#d7dce8;background:#141824;font-size:13px}.eyebrow:before{content:'✦';color:#a9b4ce;font-size:16px}h1,h2{font-family:'Space Grotesk',sans-serif;letter-spacing:-.045em}h1{margin:16px 0 8px;font-size:clamp(40px,6vw,60px);line-height:1}h1 span{color:#9ca7ff}.intro-copy h2{margin:0;color:#c4cad8;font-size:20px}.intro-copy p{max-width:650px;margin:10px 0;color:var(--muted);font-size:14px;line-height:1.6}.updated{color:#7f899d;font-size:12px}.document-visual{display:none}
.terms-grid{display:block;margin-top:40px}.side-menu{display:none}.terms-card{border:0;border-top:1px solid var(--line);border-radius:0;background:transparent;box-shadow:none;padding:0}.term-row{padding:22px 0;border-bottom:1px solid var(--line);scroll-margin-top:20px}.term-row:last-child{border-bottom:0}.term-row h2{margin:0 0 8px;color:#f3f6ff;font-size:19px;letter-spacing:-.01em}.term-row p,.term-row li{margin:0;color:var(--muted);font-size:14px;line-height:1.65;text-align:justify}.term-row ul{margin:8px 0 0;padding-left:20px}.term-row li{margin:4px 0}.term-row a{color:#9ca7ff;text-decoration:none}
@media(max-width:520px){.legal-page{padding-top:32px}.legal-nav{height:68px}.term-row p,.term-row li{font-size:13px}}
</style>
</head>
<body>
<div class="legal-shell">
<nav class="legal-nav"><a class="brand" href="{{ route('home') }}" aria-label="AgentHub home"><span class="brand-mark"><svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="11" width="18" height="10" rx="2"/><circle cx="12" cy="5" r="2"/><line x1="12" y1="7" x2="12" y2="11"/><path d="M8 15h.01M12 15h.01M16 15h.01" stroke-width="2.5"/></svg></span><span>Agent<span class="brand-accent">Hub</span></span></a></nav>
<main class="legal-page">
<section class="intro-grid"><div class="intro-copy"><h1>Terms &amp; <span>Conditions</span></h1><h2>Clear terms for your publishing workspace.</h2><p>These terms explain how you may use AgentHub to organize, review, analyze, schedule, and publish content through connected social accounts.</p><div class="updated">Effective date: September 7, 2026</div></div></section>
<section class="terms-grid"><aside class="side-menu" aria-label="Terms sections"><a href="#service"><span class="menu-icon">⌂</span>Our service</a><a href="#accounts"><span class="menu-icon">♙</span>Accounts</a><a href="#content"><span class="menu-icon">▤</span>Your content</a><a href="#connections"><span class="menu-icon">↗</span>Connections</a><a href="#acceptable"><span class="menu-icon">♢</span>Acceptable use</a><a href="#availability"><span class="menu-icon">◌</span>Availability</a><a href="#termination"><span class="menu-icon">◉</span>Termination</a><a href="#contact"><span class="menu-icon">✉</span>Contact</a></aside><div class="terms-card">
<article class="term-row" id="service"><h2>1. AgentHub service</h2><p>AgentHub provides a workspace for creating agents, uploading content, organizing a content queue, reviewing and approving posts, scheduling publishing tasks, and viewing publishing activity. Content analysis and publishing features operate according to the functionality available in your workspace and may change over time.</p></article>
<article class="term-row" id="accounts"><h2>2. Account registration and security</h2><p>You may create an account using your email address and password. You agree to provide accurate information, keep your password confidential, and accept responsibility for activity under your account. Tell us promptly if you believe your account has been accessed without permission. You must be at least able to enter into a legally binding agreement under applicable law to use the service.</p></article>
<article class="term-row" id="content"><h2>3. Your content and permission to process it</h2><p>You retain ownership of content you upload or submit to AgentHub. You confirm that you have the rights and permissions needed to upload, analyze, store, schedule, and publish that content. You grant AgentHub a limited, non-exclusive permission to process, store, display, and transmit your content only as needed to provide the features you request, including content analysis and publishing to connected platforms. We do not claim ownership of your content.</p></article>
<article class="term-row" id="connections"><h2>4. Connected social accounts</h2><p>When you connect YouTube, Facebook, Instagram, TikTok, or another supported platform, you authorize AgentHub to use the permissions granted through that platform to perform actions you request. You are responsible for complying with each platform's terms, policies, community rules, and account requirements. A platform may restrict, delay, reject, or remove a post, and AgentHub cannot guarantee delivery, reach, engagement, or continued access to a third-party platform. You may disconnect an account from the workspace.</p></article>
<article class="term-row" id="acceptable"><h2>5. Acceptable use</h2><p>You must use AgentHub lawfully and must not:</p><ul><li>use the service for fraud, impersonation, harassment, or other unlawful activity;</li><li>upload malware, harmful code, or content that you do not have permission to use;</li><li>attempt to access another person's account, credentials, or data;</li><li>use automation to interfere with the service, bypass security, or abuse a connected platform;</li><li>infringe intellectual property, privacy, publicity, or other rights; or</li><li>use AgentHub to publish content that violates applicable law or the rules of a connected platform.</li></ul></article>
<article class="term-row" id="ownership"><h2>6. AgentHub intellectual property</h2><p>The AgentHub name, logo, interface, software, and service materials are owned by or licensed to AgentHub. Except as allowed by law or expressly permitted by us, you may not copy, modify, distribute, reverse engineer, or commercially exploit them.</p></article>
<article class="term-row" id="availability"><h2>7. Availability and changes</h2><p>We aim to keep AgentHub secure and available, but we do not promise that the service will always be uninterrupted, error-free, or compatible with every device or third-party platform. We may maintain, update, suspend, or change features, including integrations, when reasonably necessary for security, legal, technical, or operational reasons.</p></article>
<article class="term-row" id="termination"><h2>8. Suspension and termination</h2><p>We may suspend or terminate access if you breach these terms, misuse AgentHub, create risk for the service or others, or if we are required to do so by law. You may stop using the service and request account deletion through the support channel associated with your workspace. Provisions that should reasonably continue after termination, including ownership, disclaimers, limitations of liability, and dispute terms, will continue to apply.</p></article>
<article class="term-row" id="disclaimer"><h2>9. Disclaimer and limitation of liability</h2><p>To the extent permitted by applicable law, AgentHub is provided on an “as is” and “as available” basis without warranties that the service will meet every need or that a scheduled post will be published successfully. To the extent permitted by law, AgentHub is not liable for indirect, incidental, special, consequential, or lost-profit damages arising from your use of the service, including failures or decisions made by connected platforms. Nothing in these terms excludes liability that cannot legally be excluded.</p></article>
<article class="term-row" id="changes"><h2>10. Changes to these terms</h2><p>We may update these Terms &amp; Conditions as AgentHub develops or legal requirements change. We will show the updated effective date on this page. Your continued use of AgentHub after an update means you accept the revised terms, to the extent permitted by law.</p></article>
<article class="term-row" id="law"><h2>11. Governing law</h2><p>These terms are governed by the applicable laws of the Republic of the Philippines, unless another law is required to apply by the circumstances or by mandatory law.</p></article>
<article class="term-row" id="contact"><h2>12. Contact us</h2><p>For questions about these terms, account deletion, or the AgentHub service, contact the AgentHub service owner through the support channel associated with your workspace. You can return to the <a href="{{ route('home') }}">AgentHub home page</a> or review our <a href="{{ route('privacy') }}">Privacy Policy</a>.</p></article>
</div></section>
</main>
</div>
</body>
</html>